### ISSUE TITLE
Ingesting/Parsing Multiple Libraries

### ISSUE THREAD

**Issue by slavakurilyak** [context-labs/autodoc#26] opened 2023-04-07 21:05 UTC
It would be great to have Autodoc ingest/parse two or more repositories/libraries, then respond in a way that combines docs in a single chat experience.

For example: 

- [LangChain Python](https://github.com/hwchase17/langchain) + [Context Labs Autodoc](https://github.com/context-labs/autodoc)
- [LangChain Python](https://github.com/hwchase17/langchain) + [OpenAI Python](https://github.com/openai/openai-python)
- [LangChain TypeScript](https://github.com/hwchase17/langchainjs) + [Microsoft TypeScript](https://github.com/microsoft/TypeScript)

**Comment by dahifi** [comment] 2023-04-08 01:11
You can do this with git submodules or just pulling multiple repos together in a single file directory before indexeing. I'm experimenting with how to combine existing indexes, but no progress there yet.

**Comment by dahifi** [comment] 2023-04-08 01:20
Also, this is a dupe of https://github.com/context-labs/autodoc/issues/13

**Closed** 2023-11-14 20:12 UTC
